from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import httpx

from backend.core.config import settings

router = APIRouter(prefix="/api/v1/chatbot", tags=["chatbot"])

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

SYSTEM_PROMPT_ES = (
    "Eres el asistente virtual de VineGuard AI, una aplicación que diagnostica "
    "enfermedades en hojas de vid (Podredumbre Negra, Esca, Tizón de la Hoja) "
    "usando modelos de inteligencia artificial (SVM, Random Forest, KNN e "
    "híbridos con redes neuronales). Ayudas a los usuarios a usar la app "
    "(subir una imagen en 'Nuevo Diagnóstico', elegir el modo de análisis, "
    "descargar reportes en PDF, Word o Excel desde 'Reportes') y a entender "
    "sus resultados. Responde siempre en español, de forma breve, clara y "
    "cordial (máximo 4-5 líneas salvo que te pidan más detalle). NO INVENTES "
    "NOMBRES CIENTÍFICOS DE HONGOS NI DATOS TÉCNICOS ESPECÍFICOS SOBRE LAS "
    "ENFERMEDADES, limítate a hablar de cómo usar la app y de los resultados "
    "que genera la IA. Aclara, solo cuando sea relevante, que el diagnóstico es "
    "una ayuda de IA y no reemplaza la evaluación de un ingeniero agrónomo o "
    "especialista fitosanitario."
)

SYSTEM_PROMPT_EN = (
    "You are the virtual assistant for VineGuard AI, an app that diagnoses "
    "grapevine leaf diseases (Black Rot, Esca, Leaf Blight) using machine "
    "learning models (SVM, Random Forest, KNN, and neural-network hybrids). "
    "You help users navigate the app (uploading an image in 'New Diagnosis', "
    "choosing the analysis mode, downloading PDF/Word/Excel reports from "
    "'Reports') and understand their results. Always answer in English, "
    "briefly, clearly and warmly (max 4-5 lines unless more detail is asked "
    "for). DO NOT INVENT SCIENTIFIC FUNGUS NAMES OR SPECIFIC TECHNICAL DATA "
    "ABOUT DISEASES, stick to talking about how to use the app and the results "
    "generated by the AI. Mention, only when relevant, that the AI diagnosis is "
    "a support tool and does not replace a professional agronomist's evaluation."
)

SYSTEM_PROMPT_PT = (
    "Você é o assistente virtual do VineGuard AI, um aplicativo que diagnostica "
    "doenças em folhas de videira (Podridão Negra, Esca, Queimadura das Folhas) "
    "usando modelos de inteligência artificial (SVM, Random Forest, KNN e "
    "híbridos com redes neurais). Ajuda os usuários a usar o app "
    "(carregar uma imagem em 'Novo Diagnóstico', escolher o modo de análise, "
    "baixar relatórios em PDF, Word ou Excel em 'Relatórios') e a entender "
    "seus resultados. Responda sempre em português, de forma breve, clara e "
    "cordial (máximo 4-5 linhas, a menos que peçam mais detalhes). NÃO INVENTE "
    "NOMES CIENTÍFICOS DE FUNGOS NEM DADOS TÉCNICOS ESPECÍFICOS SOBRE AS "
    "DOENÇAS, limite-se a falar sobre como usar o app e os resultados que a IA "
    "gera. Aclare, apenas quando for relevante, que o diagnóstico é uma ajuda de "
    "IA e não substitui a avaliação de um engenheiro agrônomo ou especialista "
    "fitossanitário."
)


class ChatMessage(BaseModel):
    role: str  # "user" o "assistant"
    content: str


class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    language: Optional[str] = "es"


class ChatResponse(BaseModel):
    response: str


async def _call_groq(messages: List[ChatMessage], language: str) -> Optional[str]:
    """Llama al LLM de Groq (gratuito). Devuelve None si no hay API key o falla."""
    if not settings.GROQ_API_KEY:
        return None

    if language == "es":
        system_prompt = SYSTEM_PROMPT_ES
    elif language == "en":
        system_prompt = SYSTEM_PROMPT_EN
    else:
        system_prompt = SYSTEM_PROMPT_PT
    payload = {
        "model": settings.GROQ_MODEL,
        "messages": (
            [{"role": "system", "content": system_prompt}]
            + [{"role": m.role, "content": m.content} for m in messages]
        ),
        "temperature": 0.4,
        "max_tokens": 350,
    }

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(
                GROQ_API_URL,
                headers={"Authorization": f"Bearer {settings.GROQ_API_KEY}"},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"].strip()
    except Exception:
        # Cualquier fallo (sin internet, key inválida, rate limit) → usar respaldo
        return None


def generate_response(messages: List[ChatMessage], language: str) -> str:
    """
    Genera una respuesta instantánea y flexible para el chatbot.
    """
    if not messages:
        if language == "es":
            return "¡Hola! Soy VineGuard AI, tu asistente virtual especializado en el diagnóstico de enfermedades de las uvas. ¿En qué puedo ayudarte hoy?"
        elif language == "en":
            return "Hello! I'm VineGuard AI, your virtual assistant specialized in grape disease diagnosis. How can I help you today?"
        else:
            return "Olá! Sou o VineGuard AI, seu assistente virtual especializado no diagnóstico de doenças da videira. Em que posso ajudar você hoje?"

    last_message = messages[-1].content.lower()

    if language == "es":
        # Saludos
        if any(greeting in last_message for greeting in [
            "hola", "hello", "hi", "buenos días", "buenas tardes", "buenas noches",
            "qué tal", "cómo estás", "holi", "holis", "holaaaa", "hola ia", "hey", "que tal"
        ]):
            return "¡Hola! ¿En qué puedo ayudarte con el diagnóstico de enfermedades de las uvas?"
        
        # Preguntas sobre cómo diagnosticar / analizar / evaluar
        elif any(keyword in last_message for keyword in [
            "diagnóstico", "diagnosis", "diagnosticar", "analizar", "analizo",
            "evaluo", "evaluar", "saber si", "cómo sé", "mi hoja tiene", "tiene enfermedad",
            "detectar", "reconocer", "qué tiene", "qué pasa con", "como veo", "cómo veo",
            "como se si", "cómo se si", "esta enferma", "está enferma", "enferma", "lo analizo",
            "como lo analizo", "cómo lo analizo", "subir foto", "subir imagen", "analizar imagen", "analizar hoja"
        ]):
            return "Para realizar un diagnóstico, ve a la sección 'Nuevo Diagnóstico' en la aplicación, sube una foto clara de una hoja o racimo de uva y haz clic en 'Analizar hoja'. La IA analizará la imagen y te dará un resultado con la predicción de la enfermedad (si la hay) y el nivel de riesgo."
        
        # Preguntas sobre precisión / exactitud de predicciones
        elif any(keyword in last_message for keyword in [
            "predicciones son", "prediccion es", "precisa", "preciso", "exacta", "exacto",
            "fiable", "fiables", "confiable", "confiables", "qué tan", "qué tan preciso",
            "qué tan exacto", "qué tan fiable", "qué tan confiable", "son exactas",
            "son precisas", "son fiables", "son confiables", "precisión", "precisión de las predicciones",
            "precision", "qué tan segura", "qué tan seguro", "seguridad"
        ]):
            return ("Las predicciones de VineGuard AI son muy precisas, pero siempre es importante:\n"
                    "- 📸 Usar fotos claras y bien iluminadas\n"
                    "- 🧑‍🌭 Consultar a un especialista (ingeniero agrónomo o fitosanitario) para confirmar diagnósticos importantes\n\n"
                    "Recuerda que esto es una herramienta de apoyo, no reemplaza el juicio profesional!")
        
        # Preguntas sobre enfermedades
        elif any(keyword in last_message for keyword in [
            "enfermedad", "disease", "enfermedades", "diseases", "qué enfermedades",
            "detectas", "puedes detectar", "detectan", "qué detectas", "qué enfermedades hay",
            "qué enfermedades puedo diagnosticar"
        ]):
            return "VineGuard AI puede detectar varias enfermedades comunes en las uvas, entre ellas: Podredumbre Negra (Black Rot), Esca, Tizón de la Hoja (Leaf Blight), Mildiu, Oídio y Botrytis."
        
        # Preguntas sobre reportes
        elif any(keyword in last_message for keyword in [
            "reporte", "report", "reportes", "reports", "descargar reporte",
            "generar reporte", "cómo descargo", "cómo genero", "descargar pdf", "descargar word", "descargar excel"
        ]):
            return "Puedes generar y descargar reportes detallados en formatos Word (.docx), PDF y Excel (.xlsx) desde la sección 'Reportes' de la aplicación."
        
        # Preguntas sobre qué preguntar / ayuda general
        elif any(keyword in last_message for keyword in [
            "qué te puedo preguntar", "qué puedo preguntarte", "qué puedes hacer",
            "ayuda", "help", "cómo funciona", "para qué sirves", "qué haces", "cómo se usa", "usar la app"
        ]):
            return ("Puedes preguntarme sobre:\n"
                    "- 📸 Cómo diagnosticar enfermedades en tus hojas de uva\n"
                    "- 🦠 Qué enfermedades podemos detectar\n"
                    "- 📄 Cómo generar y descargar reportes\n"
                    "- 💡 Cualquier duda sobre cómo usar la aplicación\n\n"
                    "¿Por dónde quieres empezar?")
        
        # Preguntas genéricas
        else:
            return ("Gracias por tu pregunta! Recuerda que puedo ayudarte con:\n"
                    "- Cómo diagnosticar enfermedades en las uvas\n"
                    "- Qué enfermedades detectamos\n"
                    "- Cómo generar reportes\n"
                    "- Precisión de las predicciones\n\n"
                    "¿Tienes alguna duda específica?")
    elif language == "en":
        # Saludos
        if any(greeting in last_message for greeting in [
            "hola", "hello", "hi", "good morning", "good afternoon", "good evening",
            "hey", "how are you", "what's up", "howdy"
        ]):
            return "Hello! How can I help you with grape disease diagnosis?"
        
        # Preguntas sobre cómo diagnosticar / analizar / evaluar
        elif any(keyword in last_message for keyword in [
            "diagnóstico", "diagnosis", "diagnosticar", "analyze", "how do i",
            "how to", "evaluate", "check if", "my leaf has", "has disease",
            "detect", "recognize", "what's wrong with", "upload photo", "upload image", "analyze image", "analyze leaf"
        ]):
            return "To perform a diagnosis, go to the 'New Diagnosis' section in the app, upload a clear photo of a grape leaf or cluster, and click 'Analyze leaf'. The AI will analyze the image and give you a result with the disease prediction (if any) and risk level."
        
        # Preguntas sobre precisión / exactitud de predicciones
        elif any(keyword in last_message for keyword in [
            "predictions are", "prediction is", "accurate", "accurately", "reliable",
            "how accurate", "how reliable", "trustworthy", "are they accurate",
            "are they reliable", "prediction accuracy", "precision", "how sure", "security"
        ]):
            return ("VineGuard AI predictions are very accurate, but it's always important:\n"
                    "- 📸 Use clear, well-lit photos\n"
                    "- 🧑‍🌭 Consult a specialist (agronomist or phytosanitary expert) to confirm important diagnoses\n\n"
                    "Remember this is a support tool, it doesn't replace professional judgment!")
        
        # Preguntas sobre enfermedades
        elif any(keyword in last_message for keyword in [
            "enfermedad", "disease", "enfermedades", "diseases", "what diseases",
            "can you detect", "do you detect", "what diseases are there", "what diseases can I diagnose"
        ]):
            return "VineGuard AI can detect several common grape diseases, including: Black Rot, Esca, Leaf Blight, Downy Mildew, Powdery Mildew, and Botrytis."
        
        # Preguntas sobre reportes
        elif any(keyword in last_message for keyword in [
            "reporte", "report", "reportes", "reports", "download report",
            "generate report", "how do i download", "how do i generate", "download pdf", "download word", "download excel"
        ]):
            return "You can generate and download detailed reports in Word (.docx), PDF, and Excel (.xlsx) formats from the 'Reports' section of the application."
        
        # Preguntas sobre qué preguntar / ayuda general
        elif any(keyword in last_message for keyword in [
            "what can i ask you", "what can you do", "help", "how does this work",
            "what do you do", "what is this for", "how to use", "use the app"
        ]):
            return ("You can ask me about:\n"
                    "- 📸 How to diagnose diseases on your grape leaves\n"
                    "- 🦠 What diseases we can detect\n"
                    "- 📄 How to generate and download reports\n"
                    "- 💡 Any questions about how to use the app\n\n"
                    "Where do you want to start?")
        
        # Preguntas genéricas
        else:
            return ("Thanks for your question! Remember I can help you with:\n"
                    "- How to diagnose grape diseases\n"
                    "- What diseases we detect\n"
                    "- How to generate reports\n"
                    "- Prediction accuracy\n\n"
                    "Do you have any specific questions?")
    else:  # Portuguese
        # Saudações
        if any(greeting in last_message for greeting in [
            "olá", "oi", "bom dia", "boa tarde", "boa noite", "como você está", "tudo bem", "hello", "hi", "tchau", "ola"
        ]):
            return "Olá! Em que posso ajudar você com o diagnóstico de doenças da videira?"
        
        # Perguntas sobre como diagnosticar / analisar / avaliar
        elif any(keyword in last_message for keyword in [
            "diagnóstico", "diagnosis", "diagnosticar", "analisar", "analizo",
            "avaliar", "saber se", "como sei", "minha folha tem", "tem doença",
            "detectar", "reconhecer", "o que tem", "o que há de errado", "como vejo",
            "como sei se", "está doente", "doente", "enviar foto", "enviar imagem", "analisar imagem", "analisar folha"
        ]):
            return "Para fazer um diagnóstico, vá para a seção 'Novo Diagnóstico' no aplicativo, envie uma foto clara de uma folha ou cacho de uva e clique em 'Analisar folha'. A IA analisará a imagem e dará um resultado com a previsão da doença (se houver) e o nível de risco."
        
        # Perguntas sobre precisão das previsões
        elif any(keyword in last_message for keyword in [
            "previsões são", "previsão é", "precisa", "preciso", "exato", "fiável",
            "confiável", "quão preciso", "quão exato", "quão fiável", "quão confiável",
            "são exatas", "são precisas", "são fiáveis", "são confiáveis", "precisão", "precisão das previsões",
            "quão seguro", "segurança"
        ]):
            return ("As previsões do VineGuard AI são muito precisas, mas é sempre importante:\n"
                    "- 📸 Usar fotos claras e bem iluminadas\n"
                    "- 🧑‍🌭 Consultar um especialista (engenheiro agrônomo ou fitossanitário) para confirmar diagnósticos importantes\n\n"
                    "Lembre-se que esta é uma ferramenta de apoio, não substitui o julgamento profissional!")
        
        # Perguntas sobre doenças
        elif any(keyword in last_message for keyword in [
            "doença", "disease", "doenças", "diseases", "quais doenças",
            "você detecta", "podem detectar", "detectam", "quais você detecta", "quais doenças existem", "quais doenças posso diagnosticar"
        ]):
            return "O VineGuard AI pode detectar várias doenças comuns nas uvas, incluindo: Podridão Negra (Black Rot), Esca, Queimadura das Folhas (Leaf Blight), Míldio, Oídio e Botrytis."
        
        # Perguntas sobre relatórios
        elif any(keyword in last_message for keyword in [
            "relatório", "report", "relatórios", "reports", "baixar relatório",
            "gerar relatório", "como faço para baixar", "como faço para gerar", "baixar pdf", "baixar word", "baixar excel"
        ]):
            return "Você pode gerar e baixar relatórios detalhados nos formatos Word (.docx), PDF e Excel (.xlsx) na seção 'Relatórios' do aplicativo."
        
        # Perguntas sobre o que perguntar / ajuda geral
        elif any(keyword in last_message for keyword in [
            "o que posso perguntar", "o que você pode fazer", "ajuda", "help", "como funciona",
            "para que serve", "o que você faz", "como usar", "usar o app"
        ]):
            return ("Você pode me perguntar sobre:\n"
                    "- 📸 Como diagnosticar doenças nas suas folhas de uva\n"
                    "- 🦠 Quais doenças podemos detectar\n"
                    "- 📄 Como gerar e baixar relatórios\n"
                    "- 💡 Qualquer dúvida sobre como usar o aplicativo\n\n"
                    "Por onde você quer começar?")
        
        # Perguntas genéricas
        else:
            return ("Obrigado por sua pergunta! Lembre-se que posso ajudar você com:\n"
                    "- Como diagnosticar doenças nas uvas\n"
                    "- Quais doenças detectamos\n"
                    "- Como gerar relatórios\n"
                    "- Precisão das previsões\n\n"
                    "Você tem alguma dúvida específica?")


@router.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Endpoint para interactuar con el chatbot de VineGuard AI.
    Usa un LLM real (Groq) cuando hay API key configurada; si no la hay,
    o la llamada falla por cualquier motivo, usa el sistema de reglas
    local como respaldo (nunca deja al usuario sin respuesta).
    """
    try:
        language = request.language if request.language in ["es", "en", "pt"] else "es"

        llm_response = await _call_groq(request.messages, language)
        if llm_response:
            return ChatResponse(response=llm_response)

        response_text = generate_response(request.messages, language)
        return ChatResponse(response=response_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error en el chatbot: {str(e)}")
